FROM node:18-alpine3.18

WORKDIR /home/app
COPY . .

EXPOSE 3050

RUN npm install -g ts-node ts-node-dev

USER node

CMD [ "sh", "-c", "[ -d node_modules ] && ts-node-dev src/index.ts || (npm install && ts-node-dev src/index.ts)" ]
