services:
  elecciones:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3050:3050"
    volumes:
      - ./:/home/app
    command: "/usr/sbin/crond -f -l 0 -L /home/app/data/logs/runCrond.log"
volumes:
  elecciones-data: